main: net.tfminecraft.vehicleframework.VehicleFramework
api-version: '1.21.10'
name: VehicleFramework
version: ${project.version}
author: Drefvelin
folia-supported: true

depend: [NBTAPI, ModelEngine, ProtocolLib, TLibs]
softdepend: [MythicMobs, CoreProtect]

commands:
  vf:
    useage: /<command>
    description: Vehicle Framework Command